/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flashcards;

/**
 *
 * @author Tracy Ayres
 */
public class FlashCards extends javax.swing.JFrame {

    /**
     * Creates new form FlashCards
     */
    public FlashCards() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardText = new javax.swing.JTextField();
        Terms = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cardText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cardText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cardText.setText("jTextField1");
        cardText.setToolTipText("");
        cardText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardTextActionPerformed(evt);
            }
        });
        getContentPane().add(cardText, java.awt.BorderLayout.CENTER);

        Terms.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Terms.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Terms.setText("jLabel1");
        getContentPane().add(Terms, java.awt.BorderLayout.PAGE_START);

        jButton1.setText("Flip");
        getContentPane().add(jButton1, java.awt.BorderLayout.PAGE_END);

        jButton2.setText(">");
        jButton2.setMaximumSize(new java.awt.Dimension(50, 23));
        jButton2.setMinimumSize(new java.awt.Dimension(50, 23));
        jButton2.setPreferredSize(new java.awt.Dimension(50, 23));
        getContentPane().add(jButton2, java.awt.BorderLayout.LINE_END);

        jButton3.setText("<");
        jButton3.setMaximumSize(new java.awt.Dimension(50, 23));
        jButton3.setMinimumSize(new java.awt.Dimension(50, 23));
        jButton3.setPreferredSize(new java.awt.Dimension(50, 23));
        getContentPane().add(jButton3, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cardTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlashCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlashCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlashCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlashCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlashCards().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Terms;
    private javax.swing.JTextField cardText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
